services:
  api_address_bucket:
    build:
      context: .
    container_name: api_address_bucket
    volumes:
      - "./../:/app/"
      - "/app/docker/"
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=myverystrongpassword
      - DATABASE_HOST=api_address_bucket_database
      - DATABASE_NAME=api_address_bucket
  api_address_bucket_database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=myverystrongpassword
    ports:
      - 3398:3306
