services:
  api_address_bucket:
    build:
      context: .
    container_name: api_address_bucket
    volumes:
      - "./../:/app/"
      - "/app/docker/"
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=myverystrongpassword
      - DATABASE_HOST=api_address_bucket_database
      - DATABASE_NAME=api_address_bucket
      - DATABASE_NAME_TEST=api_address_bucket_test
    working_dir: /app
  api_address_bucket_database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=myverystrongpassword
    ports:
      - 3398:3306
